server:
  port: 8080

jwt:
  secret: mysecretkey12345678901hfkjhkjdhkhksjdgfhjgjdkjkhfkdh23456

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: payment-service
              uri: http://localhost:4000
              predicates:
                - Path=/api/payments,/api/payments/**

            - id: order-service
              uri: http://localhost:9090
              predicates:
                - Path=/orders,/orders/**

            - id: auth-service
              uri: http://localhost:8085
              predicates:
                - Path=/auth,/auth/**

            - id: cart-service
              uri: http://localhost:9190
              predicates:
                - Path=/carts,/carts/**,/cartitems,/cartitems/**

            - id: restaurant-service
              uri: http://localhost:9098
              predicates:
                - Path=/api/restaurants,/api/restaurants/**

            - id: email-service
              uri: http://localhost:4001
              predicates:
                - Path=/api/emails,/api/emails/**

