server:
  port: 8080



spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: payment-service
              uri: http://localhost:4000
              predicates:
                - Path=/api/payments/**
            - id: order-service
              uri: http://localhost:9090
              predicates:
                - Path=/orders,/orders/**

            - id: auth-service
              uri: http://localhost:8085
              predicates:
                - Path=/auth/**

            - id: cart-service
              uri: http://localhost:9190
              predicates:
                - Path=/carts/**,/cartitems/**

            - id: restaurant-service
              uri: http://localhost:9098
              predicates:
                - Path=/api/restaurants/**

            - id: email-service
              uri: http://localhost:4001
              predicates:
                - Path=/api/emails/**

