services:
  studentmgmt_db:
    image: postgres:14.15-alpine3.21
    container_name: studentmgmt_db
    hostname: studentmgmt_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - studentmgmt_data:/var/lib/postgresql/data

  studentmgmt_db_admin:
    image: dpage/pgadmin4:latest
    container_name: studentmgmt_db_admin
    hostname: studentmgmt_db_admin
    restart: unless-stopped
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_MAX_LOGIN_ATTEMPTS: 5


volumes:
  studentmgmt_data:
    